I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 131, in script
    MC "Who am I?"
Exception: Sayer 'MC' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 131, in script
    MC "Who am I?"
  File "/Volumes/renpy-8.3.2-sdk/renpy-8.3.2-sdk/renpy/ast.py", line 2573, in execute
    Say.execute(self)
  File "/Volumes/renpy-8.3.2-sdk/renpy-8.3.2-sdk/renpy/ast.py", line 575, in execute
    who = eval_who(self.who, self.who_fast)
  File "/Volumes/renpy-8.3.2-sdk/renpy-8.3.2-sdk/renpy/ast.py", line 464, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'MC' is not defined.

macOS-14.1-arm64-arm-64bit arm64
Ren'Py 8.3.2.24090902
star team 1.0
Fri Oct 11 14:05:18 2024
